-- Local development seed (runs on `supabase db reset`, never on remote).
-- Taxonomy and exam tags are seeded by migration 20261001000010_taxonomy_seed.sql,
-- so they exist on every database, not only local ones.
