USE apti_db1;

-- Drop tables in order of dependency to avoid foreign key errors
DROP TABLE IF EXISTS `feedback_reports`;
DROP TABLE IF EXISTS `user_feedback`;
DROP TABLE IF EXISTS `user_attempts`;
DROP TABLE IF EXISTS `user_daily_log`;
DROP TABLE IF EXISTS `questions`;
DROP TABLE IF EXISTS `users`;


-- --- User Table ---
-- Stores all user information, credentials, and stats
CREATE TABLE `users` (
  `user_id` VARCHAR(12) NOT NULL,
  `google_id` VARCHAR(255) DEFAULT NULL,
  `user_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password_hash` VARCHAR(255) DEFAULT NULL COMMENT 'For email/password login',
  `score` INT DEFAULT '0',
  `level` VARCHAR(20) DEFAULT 'Beginner',
  `day_streak` INT DEFAULT '0',
  `last_login` DATETIME DEFAULT NULL,
  `answered_qids` JSON DEFAULT (JSON_ARRAY()) COMMENT 'Stores an array of QIDs the user has answered',
  `premium_level` VARCHAR(20) DEFAULT 'free' COMMENT 'For future use',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `is_banned` BOOLEAN DEFAULT FALSE COMMENT 'Admin can ban users',
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `email` (`email`),
  UNIQUE KEY `google_id` (`google_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- --- Question Table ---
-- Stores all questions. New questions generated by users are added here.
CREATE TABLE `questions` (
  `question_id` INT NOT NULL AUTO_INCREMENT,
  `qid` VARCHAR(16) NOT NULL COMMENT 'Unique public-facing question ID',
  `question_text` TEXT NOT NULL,
  `options` JSON NOT NULL COMMENT 'Array of strings, e.g., ["Opt A", "Opt B"]',
  `correct_answer_index` INT NOT NULL COMMENT '0-based index of the correct option',
  `explanation` TEXT,
  `hint` TEXT,
  `difficulty` VARCHAR(20) NOT NULL,
  `category` VARCHAR(50) NOT NULL COMMENT 'e.g., Quantitative Aptitude, Logical Reasoning',
  `generated_for_date` DATE DEFAULT NULL COMMENT 'Date for which this question was generated (for daily challenges)',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`question_id`),
  UNIQUE KEY `qid` (`qid`),
  KEY `idx_generated_for_date` (`generated_for_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- --- User Daily Log ---
-- This is the crucial new table.
-- It links a user to a specific set of question_ids for a specific day.
CREATE TABLE IF NOT EXISTS `user_daily_log` (
  `log_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(12) NOT NULL,
  `challenge_date` DATE NOT NULL,
  `question_ids_json` JSON NOT NULL COMMENT 'Array of internal question_ids [1, 5, 22]',
  PRIMARY KEY (`log_id`),
  UNIQUE KEY `user_challenge_date` (`user_id`,`challenge_date`),
  CONSTRAINT `fk_user_log` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- --- User Attempts Table ---
-- Stores each user's attempt at a daily question
CREATE TABLE IF NOT EXISTS `user_attempts` (
  `attempt_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(12) NOT NULL,
  `qid` VARCHAR(16) NOT NULL,
  `question_id` INT NOT NULL COMMENT 'Internal DB ID, for joins',
  `selected_answer_index` INT DEFAULT NULL,
  `status` VARCHAR(20) NOT NULL COMMENT 'pending, correct, wrong, hint_used, gave_up',
  `points_earned` INT DEFAULT '0',
  `attempt_date` DATE NOT NULL,
  PRIMARY KEY (`attempt_id`),
  UNIQUE KEY `user_daily_question` (`user_id`,`attempt_date`,`qid`),
  KEY `fk_user_attempts` (`user_id`),
  KEY `fk_question_attempts` (`question_id`),
  KEY `qid_index` (`qid`),
  CONSTRAINT `user_attempts_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE,
  CONSTRAINT `user_attempts_ibfk_3` FOREIGN KEY (`question_id`) REFERENCES `questions` (`question_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- --- User Feedback Table ---
-- Stores general user feedback (ratings, comments)
CREATE TABLE IF NOT EXISTS `user_feedback` (
  `feedback_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(12) NOT NULL,
  `rating` INT NOT NULL COMMENT 'Rating from 1 to 5',
  `comment` TEXT DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`feedback_id`),
  CONSTRAINT `fk_user_feedback` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- --- Feedback Reports Table ---
-- Stores reports from users about inappropriate feedback comments
CREATE TABLE IF NOT EXISTS `feedback_reports` (
  `report_id` INT NOT NULL AUTO_INCREMENT,
  `feedback_id` INT NOT NULL,
  `reporter_user_id` VARCHAR(12) NOT NULL,
  `status` VARCHAR(20) DEFAULT 'pending' COMMENT 'pending, dismissed',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`report_id`),
  UNIQUE KEY `unique_report` (`feedback_id`,`reporter_user_id`),
  CONSTRAINT `fk_report_feedback` FOREIGN KEY (`feedback_id`) REFERENCES `user_feedback` (`feedback_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_report_user` FOREIGN KEY (`reporter_user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
